### PR TITLE
Welcoming contact field

### PR DESCRIPTION
**Pull request by comradekingu**
Saw your project on Hosted Weblate. Happy to help.
Old file removed as it serves no purpose of contact, avoids meritless transfer of power, and invokes immutable characteristics counterproductively. Since I am no fan of authoritarianism, it means I can contribute freely.
The new one doesn't go out of date, and also helps gain donations and contributions :)

### CODE REVIEW

**Comment by metastable-void** [comment]
Although I do not like authoritarianism either, since this project is part of @menhera-org organization, I would like to hear from other community members.

@sasakialex @anosatsuk124 How do you think about project management and community standards? What the project guidelines should look like?

**Comment by metastable-void** [comment]
Anyway, I like the contact information clearly stated.

**Comment by metastable-void** [comment]
One reason for defining community standards is to protect everyone and to prevent me (the maintainer) from abusing its power to deny for example personalities of others.

So we should think what kind of guidelines suit the needs.

**Comment by comradekingu** [comment]
@metastable-void 
There is an unavoidable intrinsic quality to meritocracy.
Undoing it by some means of representative electorate requires a lot of bureaucracy, which is not at all impervious to takeover. That is partly the problem to solve too.

The idea here is to not escalate beyond the involved parties, and not assume allegiance of people.
If no word was heard from the community beforehand, I think removing something that dictates the community in very specific and non-community ways is warranted.

I think that all-in-all sets a good precedence, and I have full faith in your troubled relation to your own power :)

**Comment by metastable-void** [comment]
Hello, we are rewriting a CoC, this time for our all projects.

[Code of Conduct.pdf](https://github.com/user-attachments/files/17121851/Code.of.Conduct.pdf)

Feedbacks are welcome.

**Comment by metastable-void** [comment]
Updated the CoC into a more gently worded version. Closing as completed...

Thank you for the feedback!

----

If you find problems with the new Code of Conduct, please file a new issue.

**Pull request closed without merging**
